### PR TITLE
NEXUS-20632 - Use official Maven component for decryption of server connection details

### PR DESCRIPTION
**Pull request by stephenc**
Seems to resolve https://issues.sonatype.org/browse/NEXUS-20632 for me

### CODE REVIEW

**Comment by thejosh00** [comment]
looks good! +1

**Review by ybulatnikov — CHANGES_REQUESTED** [review]
Is it possible to add some tests? I see some tests were removed, but none added.

**Comment by stephenc** [comment]
The tests were for an error path on the custom secret decryption code. There is no error path with the official secrets decryption, so there is no need to test for an error path, hence the test removed was dead

**Comment by stephenc** [comment]
I don’t have access to the test infra for an integration test as I cannot resolve your internal code, so if you want an integration test you’ll have to write that as you have access to your internal repo

**Review by ybulatnikov — APPROVED** [review]
+1 approved

**Pull request merged**
